# Copy of real values used for the dev environment. DB credentials, by
# contrast, are never put in a .tfvars file; they're generated by Terraform
# and stored in Secrets Manager (see modules/rds).

aws_region = "ap-southeast-1"

azs = ["ap-southeast-1a", "ap-southeast-1b"]

frontend_vpc_cidr             = "10.0.0.0/16"
frontend_public_subnet_cidrs  = ["10.0.0.0/24", "10.0.5.0/24"]
frontend_private_subnet_cidrs = ["10.0.2.0/24", "10.0.6.0/24"]

backend_vpc_cidr              = "192.168.0.0/16"
backend_public_subnet_cidrs   = ["192.168.1.0/24", "192.168.5.0/24"]
backend_private_subnet_cidrs  = ["192.168.2.0/24", "192.168.6.0/24"]
backend_database_subnet_cidrs = ["192.168.3.0/24", "192.168.4.0/24"]

# Private DNS namespace — the ALB's cert is issued for dashboard.<this>, and
# that hostname resolves to the ALB from inside the frontend VPC. No ACM
# cert to request/validate by hand anymore: it's requested automatically
# from the Private CA in ../../pca (see main.tf).
private_domain_name = "dev.banking.internal"

frontend_container_port = 8081
backend_container_port  = 8080

# Updated by CI/CD after each image push (or bump manually + re-apply /
# force-new-deployment while testing locally).
image_tag = "latest"

backend_fargate_cpu     = 256
backend_fargate_memory  = 512
frontend_fargate_cpu    = 256
frontend_fargate_memory = 512

backend_desired_count  = 2
frontend_desired_count = 2
